#version 460 core

#include "Random.glsl"
#include "FlameParticleData.glsl"

layout (std430, binding = 0) writeonly restrict buffer SSBO_0 {
    particle particles[];
};

layout (std430, binding = 1) coherent restrict buffer SSBO_1 {
    int count;
    int indices[];
} freelist;

uniform int ParticlesToSpawn;
uniform uint Random;

// make a particle with random attributes
void MakeParticle(out particle Particle) {
    uint seed = uint(gl_GlobalInvocationID.x) + Random;
    seed = pcg_hash(seed);
    Particle.life = 2.66666666666666666666;
    Particle.velocity.xyz = rng(vec3(-0.25, 0.0, -0.25), vec3(0.25, 0.25, 0.25), seed);
    Particle.scale = 0.5;
    Particle.position = rng(vec3(-0.25, 0.0, -0.25), vec3(0.25, 0.25, 0.25), seed);
}

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
void main() {
    uint index = gl_GlobalInvocationID.x;

    if (index >= ParticlesToSpawn)
    return;

    int freeListIndex = atomicAdd(freelist.count, -1) - 1;
    if (freeListIndex < 0) {
        atomicAdd(freelist.count, 1);
        return;
    }

    int particleIndex = freelist.indices[freeListIndex];
    MakeParticle(particles[particleIndex]);
}
